### ISSUE TITLE
Error parsing Compile Remove

### ISSUE THREAD

**Issue by michaelaird** [stevenaw/vs-parse#20]
In a .net core csproj file with an element like 
```
<Compile Remove="BusinessObjects\\**" />
```
 the parser fails on a call to parseCodeFile

**Comment by stevenaw** [comment]
Thanks for raising this @michaelaird ! 
Is this something you'd be interested in submitting a PR to help fix?

**Comment by michaelaird** [comment]
Definitely can help out!

From your perspective, what is the expected result of the method if there’s
no Include attribute?
