### ISSUE TITLE
newLine regexp gets lost

### ISSUE THREAD

**Issue by delegreg** [stevenaw/vs-parse#9]
Using your parser in a subversion crawler system under Node v10, when called repeatedly, the compiled "newLine" regexp in internal.js gets lost after a few iterations, resulting in "File not found: " error.

Fixed by patching your lib in "node_modules" (in internal.js) : 

const isVsFileContents = (file) => {
  // Naive way to determine if string is a path or vs proj/sln file
  return (typeof file === 'string' && /\r|\n/g.test(file));
};

**Comment by stevenaw** [comment]
Thanks for the bug report and suggested fix @delegreg !

Is this something you'd be interested in making a formal contribution for through a pull request? I'm having a hard time replicating your issue myself, but would welcome any contribution that could help fix it for you.

**Comment by stevenaw** [comment]
@delegreg Thanks again for reporting this. I've tried making this change and it doesn't seem to break any tests.
It should be in the main branch now, and is pending release though it's difficult for me to know if it solves your issue without an easy way to repro. Please let me know if you continue to encounter issues after the next release
